def forca(erros,nome,vit,der) :

    if erros == 0 :
        print('Jogador: {} | Vitórias: {} | Derrotas: {} | Partidas: {}'.format(nome,vit,der,vit+der))
        print ()
        print ("|----- ")
        print ("|    | ")
        print ("|      ")
        print ("|      ")
        print ("|      ")
        print ("|      ")
        print ("_      ")
        print ()

    elif erros == 1 :
        print('Jogador: {} | Vitórias: {} | Derrotas: {} | Partidas: {}'.format(nome,vit,der,vit+der))
        print ()
        print ("|----- ")
        print ("|    | ")
        print ("|    O ")
        print ("|      ")
        print ("|      ")
        print ("|      ")
        print ("_      ")
        print ()

    elif erros == 2 :
        print('Jogador: {} | Vitórias: {} | Derrotas: {} | Partidas: {}'.format(nome,vit,der,vit+der))
        print ()
        print ("|----- ")
        print ("|    | ")
        print ("|    O ")
        print ("|    | ")
        print ("|    |  ")
        print ("|      ")
        print ("_      ")
        print ()

    elif erros == 3:
        print('Jogador: {} | Vitórias: {} | Derrotas: {} | Partidas: {}'.format(nome,vit,der,vit+der))
        print ()
        print ("|----- ")
        print ("|    | ")
        print ("|    O ")
        print ("|   /| ")
        print ("|    |  ")
        print ("|      ")
        print ("_      ")
        print ()

    elif erros == 4:
        print('Jogador: {} | Vitórias: {} | Derrotas: {} | Partidas: {}'.format(nome,vit,der,vit+der))
        print ()
        print ("|----- ")
        print ("|    | ")
        print ("|    O ")
        print ("|   /|\ ")
        print ("|    |  ")
        print ("|      ")
        print ("_      ")
        print ()

    elif erros == 5:
        print('Jogador: {} | Vitórias: {} | Derrotas: {} | Partidas: {}'.format(nome,vit,der,vit+der))
        print ()
        print ("|----- ")
        print ("|    | ")
        print ("|    O ")
        print ("|   /|\ ")
        print ("|    |  ")
        print ("|   /   ")
        print ("_      ")
        print ()

    elif erros == 6 :
        print('Jogador: {} | Vitórias: {} | Derrotas: {} | Partidas: {}'.format(nome,vit,der,vit+der))
        print ()
        print ("|----- ")
        print ("|    | ")
        print ("|    O ")
        print ("|   /|\ ")
        print ("|    | ")
        print ("|   / \ ")
        print ("_      ")
        print ('Não foi dessa vez :(')
        print ()
